### PR TITLE
Fixes for #35, removed RandomLib refs

### LINKED ISSUE #35: RandomLib not found
The namespace with its classes under `RandomLib` is not available, it is not defined in composer.json and not in any file.

This whole project does not work when dependencies are missing.

See https://github.com/zendframework/zend-math/blob/master/src/Rand.php#L12

`use RandomLib;`

### PR DESCRIPTION
**Pull request by ezimuel**
This PR fixes #35, removing the references to RandomLib. We used [paragonie/random_compat](https://github.com/paragonie/random_compat) instead of [ircmaxell/RandomLib](https://github.com/ircmaxell/RandomLib) since zend-math 3.0.0.

### CODE REVIEW

**Comment by ezimuel** [comment]
Fixed the assertEquals for PHPUnit 7.2+ using numeric instead of strings. This changes is related to this issue https://github.com/sebastianbergmann/phpunit/issues/3185.

File: src/Rand.php [hunk 1]
```diff
@@ -1,28 +1,17 @@
...
  * Pseudorandom number generator (PRNG)
  */
 abstract class Rand
 {
-    /**
-     * Alternative random byte generator using RandomLib
-     *
-     * @var RandomLib\Generator
-     */
-    protected static $generator = null;
```
Comment (weierophinney) [inline src/Rand.php]: Since this is marked `protected`, it should stay in, but me marked `@deprecated`, with a note that it is no longer used internally.

File: test/RandTest.php [hunk 2]
```diff
@@ -1,22 +1,24 @@
...
+use Exception;
 use PHPUnit\Framework\TestCase;
 use Zend\Math\Rand;
 
-/**
- * @group      Zend_Math
- */
 class RandTest extends TestCase
 {
+    public static $custom_random_bytes = false;
```
Comment (weierophinney) [inline test/RandTest.php]: Use `camelCase` here, please.

File: test/RandTest.php [hunk 3]
```diff
@@ -55,6 +57,13 @@ public function testNegativeRandBytesParam()
         Rand::getBytes(-1);
     }
 
+    public function testUnsupportedPlatform()
+    {
+        self::$custom_random_bytes = true;
+        $this->expectException('Zend\Math\Exception\RuntimeException');
```
Comment (weierophinney) [inline test/RandTest.php]: Import this class, and use `::class` notation here, please.

File: test/RandTest.php [hunk 4]
```diff
@@ -204,4 +213,19 @@ public function testGetStringBase64()
             $this->assertEquals(1, preg_match('#^[0-9a-zA-Z+/]+$#', $rand));
         }
     }
+
+    public function testGetNegativeSizeStringExpectException()
+    {
+        $this->expectException('Zend\Math\Exception\DomainException');
```
Comment (weierophinney) [inline test/RandTest.php]: Import this class, and use `::class` notation here, please.

File: test/TestAsset/random_bytes.php [hunk 5]
```diff
@@ -0,0 +1,17 @@
+<?php
+/**
+ * @link      http://github.com/zendframework/zend-math for the canonical source repository
+ * @copyright Copyright (c) 2005-2018 Zend Technologies USA Inc. (http://www.zend.com)
```
Comment (weierophinney) [inline test/TestAsset/random_bytes.php]: This file is introduced this year, so just `2018`.

File: test/TestAsset/random_bytes.php [hunk 6]
```diff
@@ -0,0 +1,17 @@
...
+ * @license   http://framework.zend.com/license/new-bsd New BSD License
+ */
+namespace Zend\Math;
+
+use ZendTest\Math\RandTest;
+
+function random_bytes($length)
```
Comment (weierophinney) [inline test/TestAsset/random_bytes.php]: Document the parameter and return value, please.

File: test/TestAsset/random_bytes.php [hunk 7]
```diff
@@ -0,0 +1,17 @@
...
+{
+    if (RandTest::$custom_random_bytes) {
+        throw new \Exception("Random is not supported");
```
Comment (weierophinney) [inline test/TestAsset/random_bytes.php]: Import the `Exception` class, please.

**Review by weierophinney — CHANGES_REQUESTED** [review]

**Comment by ezimuel** [comment]
@weierophinney I incorporated all your feedback, thanks!
